HCopy.exe -C config -S .\scps\ubm\f01.scp
HCopy.exe -C config -S .\scps\ubm\f10.scp
HCopy.exe -C config -S .\scps\ubm\f12.scp
HCopy.exe -C config -S .\scps\ubm\f19.scp
HCopy.exe -C config -S .\scps\ubm\f20.scp
HCopy.exe -C config -S .\scps\ubm\f21.scp
HCopy.exe -C config -S .\scps\ubm\f23.scp
HCopy.exe -C config -S .\scps\ubm\f33.scp
HCopy.exe -C config -S .\scps\ubm\f34.scp
HCopy.exe -C config -S .\scps\ubm\f40.scp
HCopy.exe -C config -S .\scps\ubm\f44.scp
HCopy.exe -C config -S .\scps\ubm\f45.scp
HCopy.exe -C config -S .\scps\ubm\f46.scp
HCopy.exe -C config -S .\scps\ubm\f47.scp
HCopy.exe -C config -S .\scps\ubm\f51.scp
HCopy.exe -C config -S .\scps\ubm\f52.scp
HCopy.exe -C config -S .\scps\ubm\f57.scp
HCopy.exe -C config -S .\scps\ubm\f67.scp
HCopy.exe -C config -S .\scps\ubm\f73.scp
HCopy.exe -C config -S .\scps\ubm\m02.scp
HCopy.exe -C config -S .\scps\ubm\m03.scp
HCopy.exe -C config -S .\scps\ubm\m04.scp
HCopy.exe -C config -S .\scps\ubm\m05.scp
HCopy.exe -C config -S .\scps\ubm\m06.scp
HCopy.exe -C config -S .\scps\ubm\m07.scp
HCopy.exe -C config -S .\scps\ubm\m08.scp
HCopy.exe -C config -S .\scps\ubm\m09.scp
HCopy.exe -C config -S .\scps\ubm\m11.scp
HCopy.exe -C config -S .\scps\ubm\m13.scp
HCopy.exe -C config -S .\scps\ubm\m14.scp
HCopy.exe -C config -S .\scps\ubm\m15.scp
HCopy.exe -C config -S .\scps\ubm\m16.scp
HCopy.exe -C config -S .\scps\ubm\m17.scp
HCopy.exe -C config -S .\scps\ubm\m18.scp
HCopy.exe -C config -S .\scps\ubm\m22.scp
HCopy.exe -C config -S .\scps\ubm\m24.scp
HCopy.exe -C config -S .\scps\ubm\m25.scp
HCopy.exe -C config -S .\scps\ubm\m26.scp
HCopy.exe -C config -S .\scps\ubm\m27.scp
HCopy.exe -C config -S .\scps\ubm\m28.scp
HCopy.exe -C config -S .\scps\ubm\m29.scp
HCopy.exe -C config -S .\scps\ubm\m30.scp
HCopy.exe -C config -S .\scps\ubm\m31.scp
HCopy.exe -C config -S .\scps\ubm\m32.scp
HCopy.exe -C config -S .\scps\ubm\m35.scp
HCopy.exe -C config -S .\scps\ubm\m36.scp
HCopy.exe -C config -S .\scps\ubm\m37.scp
HCopy.exe -C config -S .\scps\ubm\m38.scp
HCopy.exe -C config -S .\scps\ubm\m39.scp
HCopy.exe -C config -S .\scps\ubm\m41.scp
HCopy.exe -C config -S .\scps\ubm\m42.scp
HCopy.exe -C config -S .\scps\ubm\m43.scp
HCopy.exe -C config -S .\scps\ubm\m48.scp
HCopy.exe -C config -S .\scps\ubm\m49.scp
HCopy.exe -C config -S .\scps\ubm\m50.scp
HCopy.exe -C config -S .\scps\ubm\m53.scp
HCopy.exe -C config -S .\scps\ubm\m54.scp
HCopy.exe -C config -S .\scps\ubm\m55.scp
HCopy.exe -C config -S .\scps\ubm\m56.scp
HCopy.exe -C config -S .\scps\ubm\m58.scp
HCopy.exe -C config -S .\scps\ubm\m59.scp
HCopy.exe -C config -S .\scps\ubm\m60.scp
HCopy.exe -C config -S .\scps\ubm\m61.scp
HCopy.exe -C config -S .\scps\ubm\m62.scp
HCopy.exe -C config -S .\scps\ubm\m63.scp
HCopy.exe -C config -S .\scps\ubm\m64.scp
HCopy.exe -C config -S .\scps\ubm\m65.scp
HCopy.exe -C config -S .\scps\ubm\m66.scp
HCopy.exe -C config -S .\scps\ubm\m68.scp
HCopy.exe -C config -S .\scps\ubm\m69.scp
HCopy.exe -C config -S .\scps\ubm\m70.scp
HCopy.exe -C config -S .\scps\ubm\m71.scp
HCopy.exe -C config -S .\scps\ubm\m72.scp
HCopy.exe -C config -S .\scps\ubm\m74.scp
HCopy.exe -C config -S .\scps\ubm\m75.scp